# Generated by Django 3.2 on 2022-05-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Account', 'Account'), ('Enrollment', 'Enrollment'), ('Communication', 'Communication'), ('Certification', 'Certification'), ('Others', 'Others')], default='Others', max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
