# Generated by Django 3.2 on 2022-05-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=True, null=False)),
                ('topic', models.CharField(choices=[('Account', 'Account'), ('Enrollment', 'Enrollment'), ('Communication', 'Communication'), ('Certification', 'Certification'), ('Others', 'Others')], default='Others', max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
